### ISSUE TITLE
SBT build cannot resolve dependency

### ISSUE THREAD

**Issue by Eduardo-M-Cavalcanti** [pathikrit/sauron#7]
Hi,

```
resolvers += Resolver.bintrayRepo("pathikrit", "maven")

libraryDependencies += "com.github.pathikrit" %% "sauron" % "1.1.0"
```

Is producing 

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.pathikrit#sauron_2.11;1.1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
Is seems as SBT does not know how to use Resolver.bintrayRepo("pathikrit", "maven"), since a url for this repo is not listed in the build.

I have tried using sbt 0.13.7 and no success.

I tried also define a url repo like this 

resolvers += "Bintray pathikrit releases" at "https://bintray.com/artifact/download/pathikrit/maven/"

And no success either.

Currently I have added sauron jar by hand.

Do you have any tip?

Thank you.

**Comment by pathikrit** [comment]
Hmm, I see it here: http://dl.bintray.com/pathikrit/maven/com/github/pathikrit/

[Here are some examples](https://github.com/search?utf8=%E2%9C%93&q=Resolver.bintrayRepo+maven&type=Code&ref=searchresults) of using the `bintrayRepo` helper.

`sbt 0.13.7` should be good too.

Maybe try: `"bintray/pathikrit" at "http://dl.bintray.com/pathikrit/maven/"` ?

**Comment by pathikrit** [comment]
Hi, I just tried and whatever is in the README worked for me. Can you please post your project somewhere?

**Comment by Eduardo-M-Cavalcanti** [comment]
Hi,
I have just solved it.
My situation is a Play 2.3.x project, with a ./project/build.scala project file. I had to do this:

```
    val main = Project(appName, file("."))
        .enablePlugins(play.PlayScala).settings(
    // Add your own project settings here
        scalacOptions := Seq("-deprecation", "-feature", "-encoding", "UTF-8"),
        scalaVersion := "2.11.6",
        libraryDependencies ++= appDependencies,
        resolvers += Resolver.bintrayRepo("pathikrit", "maven"))
```

Before, I was putting 

```
resolvers += Resolver.bintrayRepo("pathikrit", "maven")
```

into the  ./project/plugins.sbt file where other resolvers were defined.

This has now worked:

```
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

resolvers += "Sonatype releases" at "https://oss.sonatype.org/content/repositories/releases/"

resolvers += Resolver.bintrayRepo("pathikrit", "maven")
```

**Comment by Eduardo-M-Cavalcanti** [comment]
Thanks for your help and attention.
